/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.milkdairy.users;

import java.awt.Color;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import com.milkdairy.admin.MilkDairyManagementJFrame;

/**
 *
 * @author nagarjuna
 */
public class LoginJFrame extends javax.swing.JFrame {

private JPanel milkDairyManagementJPanel;
private JFrame loginJF=this;
private LoggingService loggingService;
    /**
     * Creates new form NewJFrame
     */
    public LoginJFrame(JPanel mainPanel,LoggingService loggingService) {
        initComponents();
        this.milkDairyManagementJPanel=mainPanel;
        this.loggingService=loggingService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        userPWF = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        
        
        userNameLbl=new JLabel("User Name");
        userNameLbl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(0, 51, 204));
        userNameTF=new JTextField();
        userErrorL=new JLabel();
        userErrorL.setForeground(Color.red);
        
        userPWL = new javax.swing.JLabel("User Password");
        userPWL.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        userPWL.setForeground(new java.awt.Color(0, 51, 204));
        userPWErrorL=new JLabel();
        userPWErrorL.setForeground(Color.red);
       

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
       // setResizable(false);
        //setType(java.awt.Window.Type.POPUP);

        titleLbl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 51, 204));
        titleLbl.setText("MILK DAIRY MANAGEMENT");

        loginBtn.setText("LogIn");
        loginBtn.addActionListener(new LoginActionListener());
        
        forgetPWBtn=new JButton("Forget password");
        
//        GridLayout lay=new GridLayout(3, 2);
//        lay.setHgap(60);
//        lay.setVgap(30);
//        this.setLayout(lay);
//        this.add(userNameLbl);
//        this.add(userNameTF);
//        this.add(userPWL);
//        this.add(userPWF);
//        this.add(loginBtn);
        
          this.setLayout(null);
          Container con=this.getContentPane();
          
          titleLbl.setBounds(100, 30,300 ,40);
          userNameLbl.setBounds(40, titleLbl.getY()+50, 140, 25);
          userNameTF.setBounds(userNameLbl.getX()+100+20, titleLbl.getY()+50, 140, 25);
          userErrorL.setBounds(userNameTF.getX()+userNameTF.getWidth()+20, titleLbl.getY()+50, 140, 25);
          userPWL.setBounds(40, userNameLbl.getY()+50, 140, 20);
          userPWF.setBounds(userPWL.getX()+100+20,userNameLbl.getY()+50, 140, 25);
          userPWErrorL.setBounds(userPWF.getX()+userPWF.getWidth()+20,userPWF.getY(), 140, 25);
          
          loginBtn.setBounds(userPWF.getX()+30, userPWL.getY()+40, 70, 20);
          forgetPWBtn.setBounds(loginBtn.getX()+loginBtn.getWidth()+60, userPWL.getY()+40, 140, 20);
          
        con.add(titleLbl);
        con.add(userNameLbl);
        con.add(userNameTF);
        con.add(userPWL);
        con.add(userPWF);
        con.add(loginBtn);
        con.add(forgetPWBtn);
        con.add(userErrorL);
        con.add(userPWErrorL);
        
        this.setResizable(false);
        this.setSize(500, 300);
        //pack();
    }// </editor-fold>//GEN-END:initComponents

 
  class LoginActionListener implements ActionListener{

	@SuppressWarnings("deprecation")
	@Override
	public void actionPerformed(ActionEvent arg0) {
		if("".equals(userNameTF.getText())){
			userErrorL.setText("Can't be empty");
		}
		else if("".equals(userPWF.getText())){
			userPWErrorL.setText("Can't be empty");
		}
		else{
		loginJF.dispose();
		// TODO Auto-generated method stub
		new MilkDairyManagementJFrame(milkDairyManagementJPanel);
		}
	}
	
}
   
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel userPWL;
    private javax.swing.JPasswordField userPWF;
    private JLabel userNameLbl;
    private JTextField userNameTF;
    private javax.swing.JLabel titleLbl;
    private JButton forgetPWBtn;
    private JLabel userErrorL;
    private JLabel userPWErrorL;
  
    // End of variables declaration//GEN-END:variables
}
