/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.milkdairy.users;

import java.awt.Color;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import org.apache.log4j.Logger;

import com.milkdairy.admin.MilkDairyManagementJFrame;
import com.milkdairy.managedobjects.User;

/**
 *
 * @author nagarjuna
 */
public class LoginJFrame extends javax.swing.JFrame {
	private static final Logger LOG = Logger.getLogger(LoginJFrame.class);
	private JPanel milkDairyManagementJPanel;
	private JFrame loginJF = this;
	private LoggingService loggingService;
	private JPanel signUpJP;
	Container con;
	private boolean isSignUpDisplay = false;

	/**
	 * Creates new form NewJFrame
	 */
	public LoginJFrame(JPanel mainPanel, LoggingService loggingService) {
		initComponents();
		this.milkDairyManagementJPanel = mainPanel;
		this.loggingService = loggingService;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		titleLbl = new javax.swing.JLabel();
		userPWF = new javax.swing.JPasswordField();
		loginBtn = new javax.swing.JButton("Login");

		userNameLbl = new JLabel("User Name");
		userNameLbl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
		userNameLbl.setForeground(new java.awt.Color(0, 0, 0));
		userNameTF = new JTextField();
		userErrorL = new JLabel();
		userErrorL.setForeground(Color.red);

		userPWL = new javax.swing.JLabel("User Password");
		userPWL.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
		userPWL.setForeground(new java.awt.Color(0, 0, 0));
		userPWErrorL = new JLabel();
		userPWErrorL.setForeground(Color.red);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		titleLbl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
		titleLbl.setForeground(new java.awt.Color(0, 51, 204));
		titleLbl.setText("MILK DAIRY MANAGEMENT");

		loginBtn.setForeground(Color.WHITE);
		loginBtn.setBackground(Color.black);
		loginBtn.addActionListener(new LoginActionListener());
		loginBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));

		forgetPWBtn = new JButton("FPW");
		forgetPWBtn.setBackground(Color.black);
		forgetPWBtn.setForeground(Color.WHITE);
		forgetPWBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));

		signUpBtn = new JButton("SignUp");
		signUpBtn.setFocusPainted(false);
		signUpBtn.setMargin(new Insets(0, 0, 0, 0));
		signUpBtn.setContentAreaFilled(false);
		signUpBtn.setBorderPainted(false);
		signUpBtn.setOpaque(false);
		signUpBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
		signUpBtn.setForeground(Color.BLUE);
		signUpBtn.setFont(new java.awt.Font("Tahoma", 1, 12));

		loginImage = new JLabel();
		Icon loginBtnIcon = new ImageIcon(
				"D:\\Nagarjuna\\MyPersonal\\login_home_icon.png");
		loginImage.setIcon(loginBtnIcon);

		this.setLayout(null);
		con = this.getContentPane();

		titleLbl.setBounds(100, 30, 300, 40);
		userNameLbl.setBounds(120, titleLbl.getY() + 50, 140, 25);
		userNameTF.setBounds(userNameLbl.getX() + 100 + 20,
				titleLbl.getY() + 50, 140, 25);
		userErrorL.setBounds(userNameTF.getX() + userNameTF.getWidth() + 20,
				titleLbl.getY() + 50, 140, 25);
		userPWL.setBounds(120, userNameLbl.getY() + 50, 140, 20);
		userPWF.setBounds(userPWL.getX() + 100 + 20, userNameLbl.getY() + 50,
				140, 25);
		userPWErrorL.setBounds(userPWF.getX() + userPWF.getWidth() + 20,
				userPWF.getY(), 140, 25);

		loginBtn.setBounds(userPWF.getX() + 30, userPWL.getY() + 40, 70, 30);
		forgetPWBtn.setBounds(loginBtn.getX() + loginBtn.getWidth() + 60,
				userPWL.getY() + 40, 70, 30);
		signUpBtn.setBounds(loginBtn.getX() + loginBtn.getWidth() + 60,
				forgetPWBtn.getY() + 40, 70, 30);
		loginImage.setBounds(10, titleLbl.getY() + 20, 140, 155);

		signUpBtn.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent paramActionEvent) {
				if (!isSignUpDisplay) {
					signUpJP = showSignUpForm();
					signUpJP.setBounds(userPWL.getX() + 100,
							signUpBtn.getY() + 40, 400, 250);
					con.add(signUpJP);
					setSize(600, 600);
					isSignUpDisplay=true;
				}else{
					con.remove(signUpJP);
					setSize(600, 300);
					isSignUpDisplay=false;
				}
				revalidate();
				repaint();

			}
		});

		con.add(titleLbl);
		con.add(userNameLbl);
		con.add(userNameTF);
		con.add(userPWL);
		con.add(userPWF);
		con.add(loginBtn);
		con.add(forgetPWBtn);
		con.add(signUpBtn);
		con.add(userErrorL);
		con.add(userPWErrorL);
		con.add(loginImage);

		this.setResizable(false);
		this.setSize(600, 300);

	}

	class LoginActionListener implements ActionListener {

		@SuppressWarnings("deprecation")
		@Override
		public void actionPerformed(ActionEvent arg0) {
			if ("".equals(userNameTF.getText())) {
				userErrorL.setText("Can't be empty");
			} else if ("".equals(userPWF.getText())) {
				userPWErrorL.setText("Can't be empty");
			} else {
				loginJF.dispose();
				// TODO Auto-generated method stub
				new MilkDairyManagementJFrame(milkDairyManagementJPanel);
			}
		}
	}

	private JLabel signUpUFNameL;
	private JLabel signUpUFNameEL;
	private JTextField signUpUFNameTF;

	private JLabel signUpULNameL;
	private JLabel signUpULNameEL;
	private JTextField signUpULNameTF;

	private JLabel signUpUPhoneL;
	private JLabel signUpUPhoneEL;
	private JTextField signUpUPhoneTF;

	private JLabel signUpUEmailL;
	private JLabel signUpUEmailEL;
	private JTextField signUpUEmailTF;

	private JLabel signUpUAadharL;
	private JLabel signUpUAadharEL;
	private JTextField signUpUAadharTF;

	private JLabel signUpUIDL;
	private JLabel signUpUIDEL;
	private JTextField signUpUIDTF;

	private JLabel signUpUPWL;
	private JLabel signUpUPWEL;
	private JPasswordField signUpUPWPF;

	private JLabel signUpURPWL;
	private JLabel signUpURPWEL;
	private JPasswordField signUpURPWPF;
	
	private User validateNdGetUser(){
		String uFName=signUpUFNameTF.getText().trim();
		String uLName=signUpULNameTF.getText().trim();
		String uPhone=signUpUPhoneTF.getText().trim();
		String uEmail=signUpUEmailTF.getText().trim();
		String uAadhar=signUpUAadharTF.getText().trim();
		String uID=signUpUIDTF.getText().trim();
		String uPW=signUpUPWPF.getText().trim();
		String uRPW=signUpURPWPF.getText().trim();
		
		if("".equals(uFName)){
			
		}
		
		User user=new User();
		    return user;
	}

	private JPanel showSignUpForm() {
		JPanel panel = new JPanel();
		// panel.setBackground(Color.darkGray);
		// panel.setSize(200,200);
		GridLayout layout = new GridLayout(8, 3);
		layout.setHgap(10);
		layout.setVgap(10);
		panel.setLayout(layout);
		panel.setVisible(true);

		signUpUFNameL = new JLabel("Fisrt Name");
		signUpUFNameL.setSize(20, 60);
		signUpUFNameTF = new JTextField();
		signUpUFNameTF.setSize(20, 60);
		signUpUFNameEL = new JLabel();
		signUpUFNameEL.setSize(20, 60);

		signUpULNameL = new JLabel("Last Name");
		signUpULNameTF = new JTextField();
		signUpULNameEL = new JLabel();

		signUpUPhoneL = new JLabel("Phone");
		signUpUPhoneTF = new JTextField();
		signUpUPhoneEL = new JLabel();

		signUpUEmailL = new JLabel("Email");
		signUpUEmailTF = new JTextField();
		signUpUEmailEL = new JLabel();

		signUpUAadharL = new JLabel("Aadhar");
		signUpUAadharTF = new JTextField();
		signUpUAadharEL = new JLabel();

		signUpUIDL = new JLabel("User ID");
		signUpUIDTF = new JTextField();
		signUpUIDEL = new JLabel();

		signUpUPWL = new JLabel("Passward");
		signUpUPWPF = new JPasswordField();
		signUpUPWEL = new JLabel();

		signUpURPWL = new JLabel("RPassward");
		signUpURPWPF = new JPasswordField();
		signUpURPWEL = new JLabel();

		panel.add(signUpUFNameL);
		panel.add(signUpUFNameTF);
		panel.add(signUpUFNameEL);

		panel.add(signUpULNameL);
		panel.add(signUpULNameTF);
		panel.add(signUpULNameEL);

		panel.add(signUpUPhoneL);
		panel.add(signUpUPhoneTF);
		panel.add(signUpUPhoneEL);

		panel.add(signUpUEmailL);
		panel.add(signUpUEmailTF);
		panel.add(signUpUEmailEL);

		panel.add(signUpUAadharL);
		panel.add(signUpUAadharTF);
		panel.add(signUpUAadharEL);

		panel.add(signUpUIDL);
		panel.add(signUpUIDTF);
		panel.add(signUpUIDEL);

		panel.add(signUpUPWL);
		panel.add(signUpUPWPF);
		panel.add(signUpUPWEL);

		panel.add(signUpURPWL);
		panel.add(signUpURPWPF);
		panel.add(signUpURPWEL);

		return panel;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton loginBtn;
	private JLabel userPWL;
	private JPasswordField userPWF;
	private JLabel userNameLbl;
	private JTextField userNameTF;
	private JLabel titleLbl;
	private JButton forgetPWBtn;
	private JLabel userErrorL;
	private JLabel userPWErrorL;
	private JButton signUpBtn;
	private JLabel loginImage;

	// End of variables declaration//GEN-END:variables
}
